version: '3.9'
services:
  main:
    build:
      context: ./
      dockerfile: ./docker/main/Dockerfile
    ports:
      - 5050:5050
    networks:
      network:
        ipv4_address: 10.5.0.10
  res:
    build:
      context: ./
      dockerfile: ./docker/res/Dockerfile
    networks:
      network:
        ipv4_address: 10.5.0.11

  cli:
    build:
      context: ./
      dockerfile: ./docker/cli/Dockerfile
    ports:
      - 5000:5000
    networks:
      network:
        ipv4_address: 10.5.0.12
networks:
  network:
    driver: bridge
    name: pamw-network
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1